In [1]:
import requests
import pandas as pd
import os
import json
import time

from dotenv import load_dotenv

load_dotenv("../.env")

TMDB_ACCESS_TOKEN = os.getenv("TMDB_ACCESS_TOKEN")

print("TMDB Token Loaded:", bool(TMDB_ACCESS_TOKEN))

TMDB Token Loaded: True

In [2]:
def tmdb_request(endpoint, params=None):
    
    url = f"https://api.themoviedb.org/3{endpoint}"
    
    headers = {
        "Authorization": f"Bearer {TMDB_ACCESS_TOKEN}",
        "accept": "application/json"
    }
    
    for attempt in range(3):
        
        try:
            response = requests.get(
                url,
                headers=headers,
                params=params,
                timeout=15
            )
            
            if response.status_code == 200:
                return response.json()
            
            print(
                f"API Error: {response.status_code} | "
                f"{endpoint}"
            )
            
        except requests.exceptions.RequestException as e:
            print(
                f"Attempt {attempt + 1}/3 failed: {type(e).__name__}"
            )
            
            time.sleep(2)
    
    return None

In [3]:
def collect_movie_ids(total_pages=25):
    
    movie_ids = set()
    
    for page in range(1, total_pages + 1):
        
        data = tmdb_request(
            "/discover/movie",
            {
                "language": "en-US",
                "sort_by": "popularity.desc",
                "vote_count.gte": 50,
                "page": page
            }
        )
        
        if data is None:
            print(f"❌ Page {page} failed")
            continue
        
        for movie in data.get("results", []):
            movie_ids.add(movie["id"])
        
        print(
            f"Page {page}/{total_pages} | "
            f"Unique movies: {len(movie_ids)}"
        )
        
        time.sleep(0.2)
    
    return list(movie_ids)

In [4]:
movie_ids = collect_movie_ids(25)

print("\nTotal unique movie IDs:", len(movie_ids))

Page 1/25 | Unique movies: 20
Page 2/25 | Unique movies: 40
Page 3/25 | Unique movies: 60
Page 4/25 | Unique movies: 80
Page 5/25 | Unique movies: 96
Page 6/25 | Unique movies: 116
Page 7/25 | Unique movies: 136
Page 8/25 | Unique movies: 150
Page 9/25 | Unique movies: 170
Page 10/25 | Unique movies: 189
Page 11/25 | Unique movies: 203
Page 12/25 | Unique movies: 217
Page 13/25 | Unique movies: 237
Page 14/25 | Unique movies: 257
Page 15/25 | Unique movies: 271
Page 16/25 | Unique movies: 286
Page 17/25 | Unique movies: 299
Page 18/25 | Unique movies: 314
Page 19/25 | Unique movies: 329
Page 20/25 | Unique movies: 346
Page 21/25 | Unique movies: 361
Page 22/25 | Unique movies: 377
Page 23/25 | Unique movies: 388
Page 24/25 | Unique movies: 405
Page 25/25 | Unique movies: 421

Total unique movie IDs: 421

In [5]:
with open(
    "../data/raw/movie_ids.json",
    "w",
    encoding="utf-8"
) as f:
    
    json.dump(
        movie_ids,
        f,
        indent=2
    )

print("✅ Movie IDs saved.")

✅ Movie IDs saved.

In [6]:
def enrich_movie_large(movie_id):
    
    details = tmdb_request(
        f"/movie/{movie_id}",
        {"language": "en-US"}
    )
    
    if details is None:
        return None

    credits = tmdb_request(
        f"/movie/{movie_id}/credits",
        {"language": "en-US"}
    )
    
    keywords_data = tmdb_request(
        f"/movie/{movie_id}/keywords"
    )
    
    if credits is None:
        credits = {}
        
    if keywords_data is None:
        keywords_data = {}
    
    
    genres = [
        genre["name"]
        for genre in details.get("genres", [])
    ]
    
    cast = [
        person["name"]
        for person in credits.get("cast", [])[:10]
    ]
    
    directors = [
        person["name"]
        for person in credits.get("crew", [])
        if person.get("job") == "Director"
    ]
    
    keywords = [
        keyword["name"]
        for keyword in keywords_data.get("keywords", [])
    ]
    
    
    return {
        "id": details.get("id"),
        "title": details.get("title"),
        "overview": details.get("overview"),
        "genres": genres,
        "keywords": keywords,
        "cast": cast,
        "director": directors,
        "runtime": details.get("runtime"),
        "release_date": details.get("release_date"),
        "vote_average": details.get("vote_average"),
        "vote_count": details.get("vote_count"),
        "popularity": details.get("popularity"),
        "poster_path": details.get("poster_path"),
        "backdrop_path": details.get("backdrop_path"),
        "original_language": details.get("original_language"),
        "media_type": "movie"
    }

In [7]:
enriched_movies = []

for i, movie_id in enumerate(movie_ids, start=1):
    
    print(f"[{i}/{len(movie_ids)}] Processing ID: {movie_id}")
    
    try:
        
        movie = enrich_movie_large(movie_id)
        
        if movie is not None:
            enriched_movies.append(movie)
        
    except Exception as e:
        
        print(f"❌ Failed ID {movie_id}: {e}")
    
    
    # Save every 25 movies
    if i % 25 == 0:
        
        with open(
            "../data/raw/movies_checkpoint.json",
            "w",
            encoding="utf-8"
        ) as f:
            
            json.dump(
                enriched_movies,
                f,
                ensure_ascii=False,
                indent=2
            )
        
        print(
            f"💾 CHECKPOINT: "
            f"{len(enriched_movies)} movies saved"
        )
    
    time.sleep(0.3)

[1/421] Processing ID: 198663
[2/421] Processing ID: 13
[3/421] Processing ID: 2062
[4/421] Processing ID: 976912
[5/421] Processing ID: 1110034
[6/421] Processing ID: 22
[7/421] Processing ID: 24
[8/421] Processing ID: 313369
[9/421] Processing ID: 28
[10/421] Processing ID: 497698
[11/421] Processing ID: 122917
[12/421] Processing ID: 436270
[13/421] Processing ID: 1321008
[14/421] Processing ID: 1038392
[15/421] Processing ID: 58
[16/421] Processing ID: 62
[17/421] Processing ID: 911430
[18/421] Processing ID: 74
[19/421] Processing ID: 550988
[20/421] Processing ID: 426063
[21/421] Processing ID: 718930
[22/421] Processing ID: 866398
[23/421] Processing ID: 1308767
[24/421] Processing ID: 98
[25/421] Processing ID: 101
💾 CHECKPOINT: 25 movies saved
[26/421] Processing ID: 1368166
[27/421] Processing ID: 82023
[28/421] Processing ID: 103
[29/421] Processing ID: 106
[30/421] Processing ID: 1226863
[31/421] Processing ID: 335984
[32/421] Processing ID: 111
[33/421] Processing ID: 950387
[34/421] Processing ID: 115
[35/421] Processing ID: 829557
[36/421] Processing ID: 1007734
[37/421] Processing ID: 120
[38/421] Processing ID: 121
[39/421] Processing ID: 122
[40/421] Processing ID: 950396
[41/421] Processing ID: 128
[42/421] Processing ID: 129
[43/421] Processing ID: 73861
[44/421] Processing ID: 872585
[45/421] Processing ID: 329865
[46/421] Processing ID: 936075
[47/421] Processing ID: 1007757
[48/421] Processing ID: 1419406
[49/421] Processing ID: 1054867
[50/421] Processing ID: 1288341
💾 CHECKPOINT: 50 movies saved
[51/421] Processing ID: 106646
[52/421] Processing ID: 4247
[53/421] Processing ID: 155
[54/421] Processing ID: 12444
[55/421] Processing ID: 12445
[56/421] Processing ID: 161
[57/421] Processing ID: 170
[58/421] Processing ID: 8363
[59/421] Processing ID: 254128
[60/421] Processing ID: 1439930
[61/421] Processing ID: 755898
[62/421] Processing ID: 512200
[63/421] Processing ID: 1630409
[64/421] Processing ID: 2251
[65/421] Processing ID: 207
[66/421] Processing ID: 218
[67/421] Processing ID: 135397
[68/421] Processing ID: 238
[69/421] Processing ID: 240
[70/421] Processing ID: 1612018
[71/421] Processing ID: 315635
[72/421] Processing ID: 10494
[73/421] Processing ID: 991494
[74/421] Processing ID: 1124620
[75/421] Processing ID: 1122573
💾 CHECKPOINT: 75 movies saved
[76/421] Processing ID: 272
[77/421] Processing ID: 1368337
[78/421] Processing ID: 1659155
[79/421] Processing ID: 278
[80/421] Processing ID: 280
[81/421] Processing ID: 285
[82/421] Processing ID: 1317149
[83/421] Processing ID: 1716513
[84/421] Processing ID: 37165
[85/421] Processing ID: 1311031
[86/421] Processing ID: 698687
[87/421] Processing ID: 1339713
[88/421] Processing ID: 168259
[89/421] Processing ID: 39254
[90/421] Processing ID: 1212763
[91/421] Processing ID: 348
[92/421] Processing ID: 1241436
[93/421] Processing ID: 350
[94/421] Processing ID: 10591
[95/421] Processing ID: 18785
[96/421] Processing ID: 381284
[97/421] Processing ID: 438631
[98/421] Processing ID: 1218925
[99/421] Processing ID: 1284465
[100/421] Processing ID: 49521
💾 CHECKPOINT: 100 movies saved
[101/421] Processing ID: 156022
[102/421] Processing ID: 10625
[103/421] Processing ID: 577922
[104/421] Processing ID: 389
[105/421] Processing ID: 1175942
[106/421] Processing ID: 1159559
[107/421] Processing ID: 8587
[108/421] Processing ID: 1087891
[109/421] Processing ID: 1292695
[110/421] Processing ID: 475557
[111/421] Processing ID: 423
[112/421] Processing ID: 424
[113/421] Processing ID: 1317288
[114/421] Processing ID: 425
[115/421] Processing ID: 72105
[116/421] Processing ID: 429
[117/421] Processing ID: 10681
[118/421] Processing ID: 1108427
[119/421] Processing ID: 786892
[120/421] Processing ID: 1266127
[121/421] Processing ID: 301528
[122/421] Processing ID: 360920
[123/421] Processing ID: 16869
[124/421] Processing ID: 1315303
[125/421] Processing ID: 489
💾 CHECKPOINT: 125 movies saved
[126/421] Processing ID: 1307118
[127/421] Processing ID: 497
[128/421] Processing ID: 102899
[129/421] Processing ID: 14836
[130/421] Processing ID: 72190
[131/421] Processing ID: 1233413
[132/421] Processing ID: 383498
[133/421] Processing ID: 299534
[134/421] Processing ID: 299536
[135/421] Processing ID: 299537
[136/421] Processing ID: 539
[137/421] Processing ID: 614945
[138/421] Processing ID: 934433
[139/421] Processing ID: 550
[140/421] Processing ID: 557
[141/421] Processing ID: 558
[142/421] Processing ID: 559
[143/421] Processing ID: 564
[144/421] Processing ID: 76341
[145/421] Processing ID: 746036
[146/421] Processing ID: 801335
[147/421] Processing ID: 1430077
[148/421] Processing ID: 578
[149/421] Processing ID: 1290821
[150/421] Processing ID: 27205
💾 CHECKPOINT: 150 movies saved
[151/421] Processing ID: 585
[152/421] Processing ID: 363088
[153/421] Processing ID: 502356
[154/421] Processing ID: 598
[155/421] Processing ID: 603
[156/421] Processing ID: 354912
[157/421] Processing ID: 127585
[158/421] Processing ID: 1061474
[159/421] Processing ID: 496243
[160/421] Processing ID: 10867
[161/421] Processing ID: 630
[162/421] Processing ID: 637
[163/421] Processing ID: 1481343
[164/421] Processing ID: 640
[165/421] Processing ID: 549509
[166/421] Processing ID: 762509
[167/421] Processing ID: 490132
[168/421] Processing ID: 385687
[169/421] Processing ID: 1159831
[170/421] Processing ID: 671
[171/421] Processing ID: 672
[172/421] Processing ID: 673
[173/421] Processing ID: 674
[174/421] Processing ID: 675
[175/421] Processing ID: 1381027
💾 CHECKPOINT: 175 movies saved
[176/421] Processing ID: 617126
[177/421] Processing ID: 1325734
[178/421] Processing ID: 680
[179/421] Processing ID: 679
[180/421] Processing ID: 694
[181/421] Processing ID: 1477317
[182/421] Processing ID: 1327819
[183/421] Processing ID: 637649
[184/421] Processing ID: 330457
[185/421] Processing ID: 1280738
[186/421] Processing ID: 744
[187/421] Processing ID: 436969
[188/421] Processing ID: 767
[189/421] Processing ID: 769
[190/421] Processing ID: 271110
[191/421] Processing ID: 840464
[192/421] Processing ID: 453395
[193/421] Processing ID: 1084187
[194/421] Processing ID: 11036
[195/421] Processing ID: 293660
[196/421] Processing ID: 205596
[197/421] Processing ID: 320288
[198/421] Processing ID: 807
[199/421] Processing ID: 808
[200/421] Processing ID: 809
💾 CHECKPOINT: 200 movies saved
[201/421] Processing ID: 812
[202/421] Processing ID: 1340206
[203/421] Processing ID: 228150
[204/421] Processing ID: 76600
[205/421] Processing ID: 568124
[206/421] Processing ID: 1168190
[207/421] Processing ID: 6977
[208/421] Processing ID: 1022789
[209/421] Processing ID: 4935
[210/421] Processing ID: 297802
[211/421] Processing ID: 791373
[212/421] Processing ID: 441168
[213/421] Processing ID: 1084242
[214/421] Processing ID: 744275
[215/421] Processing ID: 1084244
[216/421] Processing ID: 855
[217/421] Processing ID: 1413976
[218/421] Processing ID: 269149
[219/421] Processing ID: 862
[220/421] Processing ID: 863
[221/421] Processing ID: 47971
[222/421] Processing ID: 1330021
[223/421] Processing ID: 822119
[224/421] Processing ID: 1241982
[225/421] Processing ID: 447365
💾 CHECKPOINT: 225 movies saved
[226/421] Processing ID: 693134
[227/421] Processing ID: 1010581
[228/421] Processing ID: 920
[229/421] Processing ID: 1301421
[230/421] Processing ID: 390062
[231/421] Processing ID: 1315772
[232/421] Processing ID: 986056
[233/421] Processing ID: 701387
[234/421] Processing ID: 263115
[235/421] Processing ID: 216015
[236/421] Processing ID: 969681
[237/421] Processing ID: 420818
[238/421] Processing ID: 803796
[239/421] Processing ID: 76757
[240/421] Processing ID: 1127384
[241/421] Processing ID: 541671
[242/421] Processing ID: 713704
[243/421] Processing ID: 1100782
[244/421] Processing ID: 1035259
[245/421] Processing ID: 402431
[246/421] Processing ID: 840705
[247/421] Processing ID: 1272837
[248/421] Processing ID: 574475
[249/421] Processing ID: 519182
[250/421] Processing ID: 508947
💾 CHECKPOINT: 250 movies saved
[251/421] Processing ID: 533533
[252/421] Processing ID: 533535
[253/421] Processing ID: 1539104
[254/421] Processing ID: 1698856
[255/421] Processing ID: 244786
[256/421] Processing ID: 7220
[257/421] Processing ID: 687163
[258/421] Processing ID: 11324
[259/421] Processing ID: 273481
[260/421] Processing ID: 1197137
[261/421] Processing ID: 1064028
[262/421] Processing ID: 1124
[263/421] Processing ID: 68718
[264/421] Processing ID: 68721
[265/421] Processing ID: 68726
[266/421] Processing ID: 1184918
[267/421] Processing ID: 1569947
[268/421] Processing ID: 296096
[269/421] Processing ID: 150689
[270/421] Processing ID: 324786
[271/421] Processing ID: 1305781
[272/421] Processing ID: 414906
[273/421] Processing ID: 1100988
[274/421] Processing ID: 507086
[275/421] Processing ID: 1250
💾 CHECKPOINT: 275 movies saved
[276/421] Processing ID: 615656
[277/421] Processing ID: 939243
[278/421] Processing ID: 396535
[279/421] Processing ID: 324857
[280/421] Processing ID: 1316092
[281/421] Processing ID: 967941
[282/421] Processing ID: 756999
[283/421] Processing ID: 1668364
[284/421] Processing ID: 361743
[285/421] Processing ID: 93456
[286/421] Processing ID: 1064213
[287/421] Processing ID: 9502
[288/421] Processing ID: 599335
[289/421] Processing ID: 359724
[290/421] Processing ID: 875828
[291/421] Processing ID: 425274
[292/421] Processing ID: 537915
[293/421] Processing ID: 539972
[294/421] Processing ID: 70981
[295/421] Processing ID: 1078605
[296/421] Processing ID: 1359
[297/421] Processing ID: 372058
[298/421] Processing ID: 283995
[299/421] Processing ID: 7518
[300/421] Processing ID: 466272
💾 CHECKPOINT: 300 movies saved
[301/421] Processing ID: 281957
[302/421] Processing ID: 558449
[303/421] Processing ID: 572802
[304/421] Processing ID: 1273221
[305/421] Processing ID: 933260
[306/421] Processing ID: 1422
[307/421] Processing ID: 284053
[308/421] Processing ID: 284054
[309/421] Processing ID: 1375646
[310/421] Processing ID: 177572
[311/421] Processing ID: 1297842
[312/421] Processing ID: 1363387
[313/421] Processing ID: 1523145
[314/421] Processing ID: 980431
[315/421] Processing ID: 931285
[316/421] Processing ID: 1495
[317/421] Processing ID: 38365
[318/421] Processing ID: 398818
[319/421] Processing ID: 1156593
[320/421] Processing ID: 1156594
[321/421] Processing ID: 370172
[322/421] Processing ID: 980477
[323/421] Processing ID: 1279493
[324/421] Processing ID: 286217
[325/421] Processing ID: 99861
💾 CHECKPOINT: 325 movies saved
[326/421] Processing ID: 77338
[327/421] Processing ID: 333339
[328/421] Processing ID: 1193501
[329/421] Processing ID: 812583
[330/421] Processing ID: 603692
[331/421] Processing ID: 1318447
[332/421] Processing ID: 181808
[333/421] Processing ID: 429617
[334/421] Processing ID: 181812
[335/421] Processing ID: 118340
[336/421] Processing ID: 552524
[337/421] Processing ID: 83533
[338/421] Processing ID: 949838
[339/421] Processing ID: 9806
[340/421] Processing ID: 5721
[341/421] Processing ID: 138843
[342/421] Processing ID: 616037
[343/421] Processing ID: 419430
[344/421] Processing ID: 259693
[345/421] Processing ID: 749170
[346/421] Processing ID: 298618
[347/421] Processing ID: 269955
[348/421] Processing ID: 870028
[349/421] Processing ID: 1072790
[350/421] Processing ID: 157336
💾 CHECKPOINT: 350 movies saved
[351/421] Processing ID: 1081003
[352/421] Processing ID: 1314481
[353/421] Processing ID: 460465
[354/421] Processing ID: 1724
[355/421] Processing ID: 976573
[356/421] Processing ID: 1726
[357/421] Processing ID: 1734
[358/421] Processing ID: 1171145
[359/421] Processing ID: 36557
[360/421] Processing ID: 1087192
[361/421] Processing ID: 1390300
[362/421] Processing ID: 1318621
[363/421] Processing ID: 1771
[364/421] Processing ID: 593643
[365/421] Processing ID: 792307
[366/421] Processing ID: 1304313
[367/421] Processing ID: 546554
[368/421] Processing ID: 141052
[369/421] Processing ID: 1306368
[370/421] Processing ID: 569094
[371/421] Processing ID: 950028
[372/421] Processing ID: 1242898
[373/421] Processing ID: 634649
[374/421] Processing ID: 315162
[375/421] Processing ID: 575265
💾 CHECKPOINT: 375 movies saved
[376/421] Processing ID: 10020
[377/421] Processing ID: 36647
[378/421] Processing ID: 36648
[379/421] Processing ID: 945961
[380/421] Processing ID: 505642
[381/421] Processing ID: 1234731
[382/421] Processing ID: 18239
[383/421] Processing ID: 1062722
[384/421] Processing ID: 1865
[385/421] Processing ID: 1097549
[386/421] Processing ID: 14160
[387/421] Processing ID: 24405
[388/421] Processing ID: 216919
[389/421] Processing ID: 38757
[390/421] Processing ID: 1893
[391/421] Processing ID: 24428
[392/421] Processing ID: 1361774
[393/421] Processing ID: 49013
[394/421] Processing ID: 12153
[395/421] Processing ID: 20352
[396/421] Processing ID: 49026
[397/421] Processing ID: 1275779
[398/421] Processing ID: 438148
[399/421] Processing ID: 1234821
[400/421] Processing ID: 75656
💾 CHECKPOINT: 400 movies saved
[401/421] Processing ID: 1930
[402/421] Processing ID: 667538
[403/421] Processing ID: 10138
[404/421] Processing ID: 49051
[405/421] Processing ID: 1228710
[406/421] Processing ID: 858024
[407/421] Processing ID: 1263532
[408/421] Processing ID: 604079
[409/421] Processing ID: 798645
[410/421] Processing ID: 1632181
[411/421] Processing ID: 1380291
[412/421] Processing ID: 1564614
[413/421] Processing ID: 1284041
[414/421] Processing ID: 1265609
[415/421] Processing ID: 530385
[416/421] Processing ID: 10195
[417/421] Processing ID: 270303
[418/421] Processing ID: 1613798
[419/421] Processing ID: 102382
[420/421] Processing ID: 454639
[421/421] Processing ID: 1083381

In [8]:
print("Movies enriched:", len(enriched_movies))

Movies enriched: 421

In [9]:
enriched_movies_df = pd.DataFrame(enriched_movies)

print("Dataset shape:", enriched_movies_df.shape)

Dataset shape: (421, 16)

In [10]:
enriched_movies_df.to_json(
    "../data/processed/movies_421_enriched.json",
    orient="records",
    indent=2,
    force_ascii=False
)

enriched_movies_df.to_csv(
    "../data/processed/movies_421_enriched.csv",
    index=False
)

print("✅ Final movie dataset saved.")

✅ Final movie dataset saved.

In [11]:
def collect_tv_ids(total_pages=25):
    
    tv_ids = set()
    
    for page in range(1, total_pages + 1):
        
        data = tmdb_request(
            "/discover/tv",
            {
                "language": "en-US",
                "sort_by": "popularity.desc",
                "vote_count.gte": 50,
                "page": page
            }
        )
        
        if data is None:
            print(f"❌ Page {page} failed")
            continue
        
        for show in data.get("results", []):
            tv_ids.add(show["id"])
        
        print(
            f"Page {page}/{total_pages} | "
            f"Unique TV shows: {len(tv_ids)}"
        )
        
        time.sleep(0.2)
    
    return list(tv_ids)

In [12]:
tv_ids = collect_tv_ids(25)

print("\nTotal unique TV IDs:", len(tv_ids))

Page 1/25 | Unique TV shows: 20
Page 2/25 | Unique TV shows: 38
Page 3/25 | Unique TV shows: 58
Page 4/25 | Unique TV shows: 76
Page 5/25 | Unique TV shows: 95
Page 6/25 | Unique TV shows: 115
Page 7/25 | Unique TV shows: 130
Page 8/25 | Unique TV shows: 149
Page 9/25 | Unique TV shows: 167
Page 10/25 | Unique TV shows: 182
Page 11/25 | Unique TV shows: 201
Page 12/25 | Unique TV shows: 218
Page 13/25 | Unique TV shows: 234
Page 14/25 | Unique TV shows: 252
Page 15/25 | Unique TV shows: 271
Page 16/25 | Unique TV shows: 291
Page 17/25 | Unique TV shows: 310
Page 18/25 | Unique TV shows: 330
Page 19/25 | Unique TV shows: 342
Page 20/25 | Unique TV shows: 353
Page 21/25 | Unique TV shows: 365
Page 22/25 | Unique TV shows: 382
Page 23/25 | Unique TV shows: 402
Page 24/25 | Unique TV shows: 419
Page 25/25 | Unique TV shows: 439

Total unique TV IDs: 439

In [13]:
with open(
    "../data/raw/tv_ids.json",
    "w",
    encoding="utf-8"
) as f:
    
    json.dump(
        tv_ids,
        f,
        indent=2
    )

print("✅ TV IDs saved.")

✅ TV IDs saved.

In [14]:
def enrich_tv_show(tv_id):
    
    # 1. TV details
    details = tmdb_request(
        f"/tv/{tv_id}",
        {"language": "en-US"}
    )
    
    if details is None:
        return None
    
    
    # 2. Credits
    credits = tmdb_request(
        f"/tv/{tv_id}/credits",
        {"language": "en-US"}
    )
    
    # 3. Keywords
    keywords_data = tmdb_request(
        f"/tv/{tv_id}/keywords"
    )
    
    if credits is None:
        credits = {}
    
    if keywords_data is None:
        keywords_data = {}
    
    
    # Genres
    genres = [
        genre["name"]
        for genre in details.get("genres", [])
    ]
    
    
    # Top 10 cast
    cast = [
        person["name"]
        for person in credits.get("cast", [])[:10]
    ]
    
    
    # TV creators
    creators = [
        person["name"]
        for person in details.get("created_by", [])
    ]
    
    
    # Keywords
    keywords = [
        keyword["name"]
        for keyword in keywords_data.get("results", [])
    ]
    
    
    return {
        "id": details.get("id"),
        "title": details.get("name"),
        "overview": details.get("overview"),
        "genres": genres,
        "keywords": keywords,
        "cast": cast,
        "director": creators,
        "runtime": (
            details.get("episode_run_time", [None])[0]
            if details.get("episode_run_time")
            else None
        ),
        "release_date": details.get("first_air_date"),
        "vote_average": details.get("vote_average"),
        "vote_count": details.get("vote_count"),
        "popularity": details.get("popularity"),
        "poster_path": details.get("poster_path"),
        "backdrop_path": details.get("backdrop_path"),
        "original_language": details.get("original_language"),
        "media_type": "tv",
        "number_of_seasons": details.get("number_of_seasons"),
        "number_of_episodes": details.get("number_of_episodes")
    }

In [15]:
enriched_tv = []

for i, tv_id in enumerate(tv_ids, start=1):
    
    print(f"[{i}/{len(tv_ids)}] Processing TV ID: {tv_id}")
    
    try:
        
        show = enrich_tv_show(tv_id)
        
        if show is not None:
            enriched_tv.append(show)
        
    except Exception as e:
        
        print(f"❌ Failed ID {tv_id}: {e}")
    
    
    # Checkpoint every 25
    if i % 25 == 0:
        
        with open(
            "../data/raw/tv_checkpoint.json",
            "w",
            encoding="utf-8"
        ) as f:
            
            json.dump(
                enriched_tv,
                f,
                ensure_ascii=False,
                indent=2
            )
        
        print(
            f"💾 CHECKPOINT: "
            f"{len(enriched_tv)} TV shows saved"
        )
    
    time.sleep(0.3)

[1/439] Processing TV ID: 200709
[2/439] Processing TV ID: 194583
[3/439] Processing TV ID: 32798
[4/439] Processing TV ID: 71712
[5/439] Processing TV ID: 36
[6/439] Processing TV ID: 290856
[7/439] Processing TV ID: 10283
[8/439] Processing TV ID: 157741
[9/439] Processing TV ID: 45
[10/439] Processing TV ID: 71728
[11/439] Processing TV ID: 157744
[12/439] Processing TV ID: 2098
[13/439] Processing TV ID: 52
[14/439] Processing TV ID: 116799
[15/439] Processing TV ID: 61511
[16/439] Processing TV ID: 2122
[17/439] Processing TV ID: 34891
[18/439] Processing TV ID: 78
[19/439] Processing TV ID: 4177
[20/439] Processing TV ID: 2129
[21/439] Processing TV ID: 45140
[22/439] Processing TV ID: 90
[23/439] Processing TV ID: 95
[24/439] Processing TV ID: 278624
[25/439] Processing TV ID: 4194
💾 CHECKPOINT: 25 TV shows saved
[26/439] Processing TV ID: 69740
[27/439] Processing TV ID: 71789
[28/439] Processing TV ID: 71790
[29/439] Processing TV ID: 2171
[30/439] Processing TV ID: 4229
[31/439] Processing TV ID: 141
[32/439] Processing TV ID: 2190
[33/439] Processing TV ID: 4239
[34/439] Processing TV ID: 4238
[35/439] Processing TV ID: 63639
[36/439] Processing TV ID: 299167
[37/439] Processing TV ID: 160
[38/439] Processing TV ID: 243875
[39/439] Processing TV ID: 245927
[40/439] Processing TV ID: 200875
[41/439] Processing TV ID: 2221
[42/439] Processing TV ID: 2224
[43/439] Processing TV ID: 4274
[44/439] Processing TV ID: 186
[45/439] Processing TV ID: 57532
[46/439] Processing TV ID: 194
[47/439] Processing TV ID: 65733
[48/439] Processing TV ID: 2261
[49/439] Processing TV ID: 6357
[50/439] Processing TV ID: 4313
💾 CHECKPOINT: 50 TV shows saved
[51/439] Processing TV ID: 61662
[52/439] Processing TV ID: 71912
[53/439] Processing TV ID: 71914
[54/439] Processing TV ID: 2287
[55/439] Processing TV ID: 2290
[56/439] Processing TV ID: 253
[57/439] Processing TV ID: 4349
[58/439] Processing TV ID: 2304
[59/439] Processing TV ID: 4357
[60/439] Processing TV ID: 30981
[61/439] Processing TV ID: 30984
[62/439] Processing TV ID: 119051
[63/439] Processing TV ID: 2316
[64/439] Processing TV ID: 269
[65/439] Processing TV ID: 39185
[66/439] Processing TV ID: 63764
[67/439] Processing TV ID: 4376
[68/439] Processing TV ID: 63770
[69/439] Processing TV ID: 4384
[70/439] Processing TV ID: 4385
[71/439] Processing TV ID: 74016
[72/439] Processing TV ID: 291
[73/439] Processing TV ID: 4386
[74/439] Processing TV ID: 2345
[75/439] Processing TV ID: 2352
💾 CHECKPOINT: 75 TV shows saved
[76/439] Processing TV ID: 10545
[77/439] Processing TV ID: 2354
[78/439] Processing TV ID: 14658
[79/439] Processing TV ID: 4419
[80/439] Processing TV ID: 6467
[81/439] Processing TV ID: 8514
[82/439] Processing TV ID: 2370
[83/439] Processing TV ID: 96580
[84/439] Processing TV ID: 223564
[85/439] Processing TV ID: 2384
[86/439] Processing TV ID: 211288
[87/439] Processing TV ID: 199001
[88/439] Processing TV ID: 39269
[89/439] Processing TV ID: 39272
[90/439] Processing TV ID: 57706
[91/439] Processing TV ID: 78191
[92/439] Processing TV ID: 61818
[93/439] Processing TV ID: 4482
[94/439] Processing TV ID: 100757
[95/439] Processing TV ID: 65942
[96/439] Processing TV ID: 2455
[97/439] Processing TV ID: 31132
[98/439] Processing TV ID: 2473
[99/439] Processing TV ID: 39340
[100/439] Processing TV ID: 108978
💾 CHECKPOINT: 100 TV shows saved
[101/439] Processing TV ID: 39351
[102/439] Processing TV ID: 61889
[103/439] Processing TV ID: 4546
[104/439] Processing TV ID: 250307
[105/439] Processing TV ID: 22980
[106/439] Processing TV ID: 4551
[107/439] Processing TV ID: 456
[108/439] Processing TV ID: 94664
[109/439] Processing TV ID: 4556
[110/439] Processing TV ID: 33238
[111/439] Processing TV ID: 74204
[112/439] Processing TV ID: 2527
[113/439] Processing TV ID: 61923
[114/439] Processing TV ID: 484
[115/439] Processing TV ID: 246246
[116/439] Processing TV ID: 4582
[117/439] Processing TV ID: 68073
[118/439] Processing TV ID: 4586
[119/439] Processing TV ID: 66025
[120/439] Processing TV ID: 4588
[121/439] Processing TV ID: 4589
[122/439] Processing TV ID: 498
[123/439] Processing TV ID: 12786
[124/439] Processing TV ID: 500
[125/439] Processing TV ID: 502
💾 CHECKPOINT: 125 TV shows saved
[126/439] Processing TV ID: 4598
[127/439] Processing TV ID: 4601
[128/439] Processing TV ID: 4604
[129/439] Processing TV ID: 82428
[130/439] Processing TV ID: 4607
[131/439] Processing TV ID: 94722
[132/439] Processing TV ID: 4614
[133/439] Processing TV ID: 4616
[134/439] Processing TV ID: 129552
[135/439] Processing TV ID: 82452
[136/439] Processing TV ID: 4629
[137/439] Processing TV ID: 4630
[138/439] Processing TV ID: 2593
[139/439] Processing TV ID: 31268
[140/439] Processing TV ID: 549
[141/439] Processing TV ID: 59941
[142/439] Processing TV ID: 76331
[143/439] Processing TV ID: 127532
[144/439] Processing TV ID: 4656
[145/439] Processing TV ID: 57911
[146/439] Processing TV ID: 2625
[147/439] Processing TV ID: 580
[148/439] Processing TV ID: 14929
[149/439] Processing TV ID: 607
[150/439] Processing TV ID: 37472
💾 CHECKPOINT: 150 TV shows saved
[151/439] Processing TV ID: 2661
[152/439] Processing TV ID: 615
[153/439] Processing TV ID: 51817
[154/439] Processing TV ID: 107113
[155/439] Processing TV ID: 2673
[156/439] Processing TV ID: 2674
[157/439] Processing TV ID: 2691
[158/439] Processing TV ID: 14981
[159/439] Processing TV ID: 651
[160/439] Processing TV ID: 655
[161/439] Processing TV ID: 127635
[162/439] Processing TV ID: 2710
[163/439] Processing TV ID: 105113
[164/439] Processing TV ID: 60059
[165/439] Processing TV ID: 107171
[166/439] Processing TV ID: 12971
[167/439] Processing TV ID: 2734
[168/439] Processing TV ID: 688
[169/439] Processing TV ID: 693
[170/439] Processing TV ID: 76479
[171/439] Processing TV ID: 709
[172/439] Processing TV ID: 2778
[173/439] Processing TV ID: 60797
[174/439] Processing TV ID: 45790
[175/439] Processing TV ID: 37606
💾 CHECKPOINT: 175 TV shows saved
[176/439] Processing TV ID: 94954
[177/439] Processing TV ID: 764
[178/439] Processing TV ID: 82684
[179/439] Processing TV ID: 99071
[180/439] Processing TV ID: 41727
[181/439] Processing TV ID: 94997
[182/439] Processing TV ID: 790
[183/439] Processing TV ID: 76572
[184/439] Processing TV ID: 797
[185/439] Processing TV ID: 45857
[186/439] Processing TV ID: 84773
[187/439] Processing TV ID: 82728
[188/439] Processing TV ID: 37678
[189/439] Processing TV ID: 37680
[190/439] Processing TV ID: 236338
[191/439] Processing TV ID: 2875
[192/439] Processing TV ID: 2883
[193/439] Processing TV ID: 219971
[194/439] Processing TV ID: 240456
[195/439] Processing TV ID: 31572
[196/439] Processing TV ID: 273240
[197/439] Processing TV ID: 2912
[198/439] Processing TV ID: 873
[199/439] Processing TV ID: 80748
[200/439] Processing TV ID: 70523
💾 CHECKPOINT: 200 TV shows saved
[201/439] Processing TV ID: 76669
[202/439] Processing TV ID: 2942
[203/439] Processing TV ID: 45950
[204/439] Processing TV ID: 322430
[205/439] Processing TV ID: 287620
[206/439] Processing TV ID: 900
[207/439] Processing TV ID: 902
[208/439] Processing TV ID: 2962
[209/439] Processing TV ID: 205715
[210/439] Processing TV ID: 918
[211/439] Processing TV ID: 15260
[212/439] Processing TV ID: 82856
[213/439] Processing TV ID: 82873
[214/439] Processing TV ID: 3034
[215/439] Processing TV ID: 84958
[216/439] Processing TV ID: 37854
[217/439] Processing TV ID: 203744
[218/439] Processing TV ID: 41956
[219/439] Processing TV ID: 33765
[220/439] Processing TV ID: 17380
[221/439] Processing TV ID: 226285
[222/439] Processing TV ID: 125935
[223/439] Processing TV ID: 220150
[224/439] Processing TV ID: 1018
[225/439] Processing TV ID: 1021
💾 CHECKPOINT: 225 TV shows saved
[226/439] Processing TV ID: 21510
[227/439] Processing TV ID: 42009
[228/439] Processing TV ID: 125988
[229/439] Processing TV ID: 3137
[230/439] Processing TV ID: 259140
[231/439] Processing TV ID: 87108
[232/439] Processing TV ID: 126027
[233/439] Processing TV ID: 1100
[234/439] Processing TV ID: 85077
[235/439] Processing TV ID: 33880
[236/439] Processing TV ID: 103516
[237/439] Processing TV ID: 62560
[238/439] Processing TV ID: 11366
[239/439] Processing TV ID: 91239
[240/439] Processing TV ID: 33907
[241/439] Processing TV ID: 103540
[242/439] Processing TV ID: 136311
[243/439] Processing TV ID: 40075
[244/439] Processing TV ID: 70796
[245/439] Processing TV ID: 60572
[246/439] Processing TV ID: 60574
[247/439] Processing TV ID: 95396
[248/439] Processing TV ID: 31911
[249/439] Processing TV ID: 70824
[250/439] Processing TV ID: 60585
💾 CHECKPOINT: 250 TV shows saved
[251/439] Processing TV ID: 66732
[252/439] Processing TV ID: 31917
[253/439] Processing TV ID: 72879
[254/439] Processing TV ID: 62643
[255/439] Processing TV ID: 46260
[256/439] Processing TV ID: 44217
[257/439] Processing TV ID: 62650
[258/439] Processing TV ID: 111803
[259/439] Processing TV ID: 1215
[260/439] Processing TV ID: 1220
[261/439] Processing TV ID: 124101
[262/439] Processing TV ID: 17610
[263/439] Processing TV ID: 60622
[264/439] Processing TV ID: 46296
[265/439] Processing TV ID: 46298
[266/439] Processing TV ID: 93405
[267/439] Processing TV ID: 62688
[268/439] Processing TV ID: 21728
[269/439] Processing TV ID: 56559
[270/439] Processing TV ID: 62710
[271/439] Processing TV ID: 95479
[272/439] Processing TV ID: 31991
[273/439] Processing TV ID: 5368
[274/439] Processing TV ID: 56570
[275/439] Processing TV ID: 95480
💾 CHECKPOINT: 275 TV shows saved
[276/439] Processing TV ID: 21755
[277/439] Processing TV ID: 5371
[278/439] Processing TV ID: 138502
[279/439] Processing TV ID: 97546
[280/439] Processing TV ID: 60694
[281/439] Processing TV ID: 120089
[282/439] Processing TV ID: 245026
[283/439] Processing TV ID: 60708
[284/439] Processing TV ID: 113962
[285/439] Processing TV ID: 60735
[286/439] Processing TV ID: 95557
[287/439] Processing TV ID: 226637
[288/439] Processing TV ID: 60761
[289/439] Processing TV ID: 210268
[290/439] Processing TV ID: 77169
[291/439] Processing TV ID: 1395
[292/439] Processing TV ID: 1396
[293/439] Processing TV ID: 95603
[294/439] Processing TV ID: 1398
[295/439] Processing TV ID: 1399
[296/439] Processing TV ID: 1400
[297/439] Processing TV ID: 1402
[298/439] Processing TV ID: 1403
[299/439] Processing TV ID: 3452
[300/439] Processing TV ID: 1405
💾 CHECKPOINT: 300 TV shows saved
[301/439] Processing TV ID: 220542
[302/439] Processing TV ID: 1407
[303/439] Processing TV ID: 1408
[304/439] Processing TV ID: 1409
[305/439] Processing TV ID: 60802
[306/439] Processing TV ID: 1411
[307/439] Processing TV ID: 1412
[308/439] Processing TV ID: 1413
[309/439] Processing TV ID: 62852
[310/439] Processing TV ID: 1415
[311/439] Processing TV ID: 1416
[312/439] Processing TV ID: 1417
[313/439] Processing TV ID: 1418
[314/439] Processing TV ID: 1419
[315/439] Processing TV ID: 1420
[316/439] Processing TV ID: 1421
[317/439] Processing TV ID: 1422
[318/439] Processing TV ID: 1414
[319/439] Processing TV ID: 1431
[320/439] Processing TV ID: 1433
[321/439] Processing TV ID: 1434
[322/439] Processing TV ID: 1435
[323/439] Processing TV ID: 1438
[324/439] Processing TV ID: 91555
[325/439] Processing TV ID: 1450
💾 CHECKPOINT: 325 TV shows saved
[326/439] Processing TV ID: 19885
[327/439] Processing TV ID: 81329
[328/439] Processing TV ID: 69050
[329/439] Processing TV ID: 60863
[330/439] Processing TV ID: 46533
[331/439] Processing TV ID: 81356
[332/439] Processing TV ID: 42444
[333/439] Processing TV ID: 1486
[334/439] Processing TV ID: 1489
[335/439] Processing TV ID: 75219
[336/439] Processing TV ID: 58841
[337/439] Processing TV ID: 1508
[338/439] Processing TV ID: 3562
[339/439] Processing TV ID: 3570
[340/439] Processing TV ID: 34307
[341/439] Processing TV ID: 1549
[342/439] Processing TV ID: 1554
[343/439] Processing TV ID: 278043
[344/439] Processing TV ID: 77341
[345/439] Processing TV ID: 3626
[346/439] Processing TV ID: 93740
[347/439] Processing TV ID: 85552
[348/439] Processing TV ID: 5687
[349/439] Processing TV ID: 245312
[350/439] Processing TV ID: 67136
💾 CHECKPOINT: 350 TV shows saved
[351/439] Processing TV ID: 1606
[352/439] Processing TV ID: 1620
[353/439] Processing TV ID: 1621
[354/439] Processing TV ID: 1622
[355/439] Processing TV ID: 3670
[356/439] Processing TV ID: 95842
[357/439] Processing TV ID: 1639
[358/439] Processing TV ID: 67178
[359/439] Processing TV ID: 79481
[360/439] Processing TV ID: 67198
[361/439] Processing TV ID: 61056
[362/439] Processing TV ID: 1667
[363/439] Processing TV ID: 1668
[364/439] Processing TV ID: 1685
[365/439] Processing TV ID: 95897
[366/439] Processing TV ID: 32415
[367/439] Processing TV ID: 73375
[368/439] Processing TV ID: 97951
[369/439] Processing TV ID: 278178
[370/439] Processing TV ID: 3750
[371/439] Processing TV ID: 1705
[372/439] Processing TV ID: 7869
[373/439] Processing TV ID: 276161
[374/439] Processing TV ID: 63174
[375/439] Processing TV ID: 34524
💾 CHECKPOINT: 375 TV shows saved
[376/439] Processing TV ID: 241372
[377/439] Processing TV ID: 206559
[378/439] Processing TV ID: 153312
[379/439] Processing TV ID: 48866
[380/439] Processing TV ID: 79593
[381/439] Processing TV ID: 18165
[382/439] Processing TV ID: 1781
[383/439] Processing TV ID: 61175
[384/439] Processing TV ID: 100088
[385/439] Processing TV ID: 48891
[386/439] Processing TV ID: 63247
[387/439] Processing TV ID: 1823
[388/439] Processing TV ID: 5920
[389/439] Processing TV ID: 38693
[390/439] Processing TV ID: 61222
[391/439] Processing TV ID: 46896
[392/439] Processing TV ID: 65334
[393/439] Processing TV ID: 67384
[394/439] Processing TV ID: 202555
[395/439] Processing TV ID: 1855
[396/439] Processing TV ID: 1871
[397/439] Processing TV ID: 1877
[398/439] Processing TV ID: 112470
[399/439] Processing TV ID: 32608
[400/439] Processing TV ID: 10083
💾 CHECKPOINT: 400 TV shows saved
[401/439] Processing TV ID: 63333
[402/439] Processing TV ID: 69478
[403/439] Processing TV ID: 46952
[404/439] Processing TV ID: 126824
[405/439] Processing TV ID: 49009
[406/439] Processing TV ID: 73586
[407/439] Processing TV ID: 49011
[408/439] Processing TV ID: 1908
[409/439] Processing TV ID: 1911
[410/439] Processing TV ID: 79744
[411/439] Processing TV ID: 1920
[412/439] Processing TV ID: 87940
[413/439] Processing TV ID: 128904
[414/439] Processing TV ID: 106379
[415/439] Processing TV ID: 225171
[416/439] Processing TV ID: 1940
[417/439] Processing TV ID: 44953
[418/439] Processing TV ID: 57243
[419/439] Processing TV ID: 83867
[420/439] Processing TV ID: 110492
[421/439] Processing TV ID: 247718
[422/439] Processing TV ID: 63401
[423/439] Processing TV ID: 18347
[424/439] Processing TV ID: 10160
[425/439] Processing TV ID: 210865
💾 CHECKPOINT: 425 TV shows saved
[426/439] Processing TV ID: 4018
[427/439] Processing TV ID: 32692
[428/439] Processing TV ID: 1973
[429/439] Processing TV ID: 1972
[430/439] Processing TV ID: 12225
[431/439] Processing TV ID: 61378
[432/439] Processing TV ID: 61381
[433/439] Processing TV ID: 241609
[434/439] Processing TV ID: 2004
[435/439] Processing TV ID: 32726
[436/439] Processing TV ID: 4057
[437/439] Processing TV ID: 4068
[438/439] Processing TV ID: 2026
[439/439] Processing TV ID: 4087

In [16]:
print("TV shows enriched:", len(enriched_tv))

TV shows enriched: 439

In [17]:
enriched_tv_df = pd.DataFrame(enriched_tv)

print("TV Dataset Shape:", enriched_tv_df.shape)

TV Dataset Shape: (439, 18)

In [18]:
catalogue_df = pd.concat(
    [
        enriched_movies_df,
        enriched_tv_df
    ],
    ignore_index=True
)

print("Final Catalogue Shape:", catalogue_df.shape)

Final Catalogue Shape: (860, 18)

In [19]:
catalogue_df["media_type"].value_counts()

media_type
tv       439
movie    421
Name: count, dtype: int64

In [20]:
catalogue_df[
    [
        "title",
        "media_type",
        "genres",
        "keywords",
        "cast",
        "director"
    ]
].head(10)

,title,media_type,genres,keywords,cast,director
0,The Maze Runner,movie,"[Action, Mystery, Science Fiction, Thriller]","[based on novel or book, escape, dystopia, maz...","[Dylan O'Brien, Kaya Scodelario, Thomas Brodie...",[Wes Ball]
1,Forrest Gump,movie,"[Comedy, Drama, Romance]","[new year's eve, vietnam war, vietnam veteran,...","[Tom Hanks, Robin Wright, Gary Sinise, Sally F...",[Robert Zemeckis]
2,Ratatouille,movie,"[Animation, Comedy, Family, Fantasy]","[work, sibling relationship, paris, france, ex...","[Patton Oswalt, Ian Holm, Lou Romano, Brian De...",[Brad Bird]
3,Graphic Desires,movie,"[Thriller, Crime]","[infidelity, cheating, killing, murder, softco...","[David Wayman, Sian Altman, May Kelly, Ocean M...",[Andy Edwards]
4,Kraken,movie,"[Horror, Action, Thriller]","[sea monster, norwegian folklore, cautionary]","[Sara Khorami, Mikkel Bratt Silset, Ingvild Ho...",[Pål Øie]
5,Pirates of the Caribbean: The Curse of the Bla...,movie,"[Adventure, Fantasy, Action]","[ship, blacksmith, gold, exotic island, govern...","[Johnny Depp, Geoffrey Rush, Orlando Bloom, Ke...",[Gore Verbinski]
6,Kill Bill: Vol. 1,movie,"[Action, Crime]","[martial arts, japan, kung fu, sword, yakuza, ...","[Uma Thurman, Lucy Liu, Vivica A. Fox, Daryl H...",[Quentin Tarantino]
7,La La Land,movie,"[Comedy, Drama, Romance]","[dancing, dance, jazz, melancholy, musical, am...","[Ryan Gosling, Emma Stone, John Legend, Rosema...",[Damien Chazelle]
8,Apocalypse Now,movie,"[Drama, War]","[guerrilla warfare, vietnam war, journalist, m...","[Martin Sheen, Marlon Brando, Frederic Forrest...",[Francis Ford Coppola]
9,Black Widow,movie,"[Action, Adventure, Science Fiction]","[assassin, hero, spy, kgb, based on comic, fem...","[Scarlett Johansson, Florence Pugh, Rachel Wei...",[Cate Shortland]

In [21]:
catalogue_df.to_json(
    "../data/processed/movie_tv_catalogue.json",
    orient="records",
    indent=2,
    force_ascii=False
)

catalogue_df.to_csv(
    "../data/processed/movie_tv_catalogue.csv",
    index=False
)

print("✅ Unified Movie + TV catalogue saved.")

✅ Unified Movie + TV catalogue saved.

In [22]:
catalogue_df["title"].duplicated().sum()

np.int64(9)

In [23]:
catalogue_df[
    [
        "overview",
        "genres",
        "keywords",
        "cast",
        "director"
    ]
].isna().sum()

overview    0
genres      0
keywords    0
cast        0
director    0
dtype: int64

In [24]:
catalogue_df["media_type"].value_counts()

media_type
tv       439
movie    421
Name: count, dtype: int64

In [25]:
catalogue_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 860 entries, 0 to 859
Data columns (total 18 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id                  860 non-null    int64
 1   title               860 non-null    str
 2   overview            860 non-null    str
 3   genres              860 non-null    object
 4   keywords            860 non-null    object
 5   cast                860 non-null    object
 6   director            860 non-null    object
 7   runtime             634 non-null    float64
 8   release_date        860 non-null    str
 9   vote_average        860 non-null    float64
 10  vote_count          860 non-null    int64
 11  popularity          860 non-null    float64
 12  poster_path         860 non-null    str
 13  backdrop_path       860 non-null    str
 14  original_language   860 non-null    str
 15  media_type          860 non-null    str
 16  number_of_seasons   439 non-null    float64
 17  number_of_episodes  439 non-null    float64
dtypes: float64(5), int64(2), object(4), str(7)
memory usage: 121.1+ KB

In [28]:
catalogue_df["title"].duplicated().sum()
catalogue_df[
    ["overview", "genres", "keywords", "cast", "director"]
].isna().sum()
catalogue_df["media_type"].value_counts()
catalogue_df.shape

(860, 18)

In [29]:
print("Duplicate titles:", catalogue_df["title"].duplicated().sum())

print("\nMissing values:")
print(
    catalogue_df[
        ["overview", "genres", "keywords", "cast", "director"]
    ].isna().sum()
)

print("\nMedia types:")
print(catalogue_df["media_type"].value_counts())

print("\nDataset shape:")
print(catalogue_df.shape)

Duplicate titles: 9

Missing values:
overview    0
genres      0
keywords    0
cast        0
director    0
dtype: int64

Media types:
media_type
tv       439
movie    421
Name: count, dtype: int64

Dataset shape:
(860, 18)

In [30]:
import ast
import re

In [31]:
text_columns = [
    "overview",
    "genres",
    "keywords",
    "cast",
    "director"
]

for col in text_columns:
    catalogue_df[col] = catalogue_df[col].fillna("")

In [32]:
def clean_text(value):
    
    if isinstance(value, list):
        value = " ".join(map(str, value))
    
    value = str(value)
    
    value = value.lower()
    
    value = re.sub(r"[^a-zA-Z0-9\s]", " ", value)
    
    value = re.sub(r"\s+", " ", value).strip()
    
    return value

In [33]:
for col in text_columns:
    catalogue_df[col] = catalogue_df[col].apply(clean_text)

In [34]:
catalogue_df["combined_text"] = (
    catalogue_df["overview"] + " " +
    catalogue_df["genres"] + " " +
    catalogue_df["keywords"] + " " +
    catalogue_df["cast"] + " " +
    catalogue_df["director"]
)

In [35]:
print(
    catalogue_df[
        ["title", "combined_text"]
    ].iloc[0]
)

title                                              The Maze Runner
combined_text    a teenager with no memory of his past finds hi...
Name: 0, dtype: str

In [36]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(
    stop_words="english",
    max_features=10000,
    ngram_range=(1, 2)
)

tfidf_matrix = tfidf.fit_transform(
    catalogue_df["combined_text"]
)

print("TF-IDF Matrix Shape:", tfidf_matrix.shape)

TF-IDF Matrix Shape: (860, 10000)

In [37]:
from sklearn.metrics.pairwise import cosine_similarity

similarity_matrix = cosine_similarity(tfidf_matrix)

print("Similarity Matrix Shape:", similarity_matrix.shape)

Similarity Matrix Shape: (860, 860)

In [38]:
def recommend(title, top_n=10):
    
    # Find the movie/show
    matches = catalogue_df[
        catalogue_df["title"].str.lower() == title.lower()
    ]
    
    if matches.empty:
        print("❌ Title not found.")
        return pd.DataFrame()
    
    # Get its index
    index = matches.index[0]
    
    # Get similarity scores
    scores = list(enumerate(similarity_matrix[index]))
    
    # Sort from highest to lowest
    scores = sorted(
        scores,
        key=lambda x: x[1],
        reverse=True
    )
    
    recommendations = []
    
    # Skip the title itself
    for movie_index, score in scores[1:top_n + 1]:
        
        recommendations.append({
            "title": catalogue_df.iloc[movie_index]["title"],
            "media_type": catalogue_df.iloc[movie_index]["media_type"],
            "similarity_score": round(score * 100, 2)
        })
    
    return pd.DataFrame(recommendations)

In [39]:
recommend(
    "Spider-Man: Brand New Day",
    top_n=10
)

                                 title media_type  similarity_score
0              Spider-Man: No Way Home      movie             38.87
1               Spider-Man: Homecoming      movie             34.95
2            Spider-Man: Far From Home      movie             32.18
3  Spider-Man: Across the Spider-Verse      movie             25.58
4             The Amazing Spider-Man 2      movie             24.45
5                           Spider-Man      movie             23.67
6               The Amazing Spider-Man      movie             20.50
7                         Spider-Man 2      movie             17.79
8                        Thunderbolts*      movie             16.39
9                       Thor: Ragnarok      movie             15.86

In [40]:
def recommend_for_user(liked_titles, top_n=10):
    
    liked_indices = []
    
    for title in liked_titles:
        
        matches = catalogue_df[
            catalogue_df["title"].str.lower() == title.lower()
        ]
        
        if matches.empty:
            print(f"⚠️ Title not found: {title}")
        else:
            liked_indices.append(matches.index[0])
    
    
    if not liked_indices:
        print("❌ No valid titles found.")
        return pd.DataFrame()
    
    
    # Get TF-IDF vectors of liked titles
    liked_vectors = tfidf_matrix[liked_indices]
    
    # Create user's taste vector
    user_vector = liked_vectors.mean(axis=0)
    
    
    # Compare user taste with every title
    user_similarity = cosine_similarity(
        user_vector,
        tfidf_matrix
    ).flatten()
    
    
    # Rank titles
    ranked_indices = user_similarity.argsort()[::-1]
    
    
    recommendations = []
    
    for index in ranked_indices:
        
        # Don't recommend something the user already likes
        if index in liked_indices:
            continue
        
        recommendations.append({
            "title": catalogue_df.iloc[index]["title"],
            "media_type": catalogue_df.iloc[index]["media_type"],
            "similarity_score": round(
                user_similarity[index] * 100,
                2
            )
        })
        
        if len(recommendations) == top_n:
            break
    
    
    return pd.DataFrame(recommendations)

In [42]:
def recommend_for_user(liked_titles, top_n=10):

    liked_indices = []

    for title in liked_titles:

        matches = catalogue_df[
            catalogue_df["title"].str.lower() == title.lower()
        ]

        if matches.empty:
            print(f"⚠️ Title not found: {title}")
        else:
            liked_indices.append(matches.index[0])

    if not liked_indices:
        print("❌ No valid titles found.")
        return pd.DataFrame()

    # Get TF-IDF vectors of liked titles
    liked_vectors = tfidf_matrix[liked_indices]

    # Create user taste vector
    user_vector = np.asarray(
        liked_vectors.mean(axis=0)
    )

    # Compare user taste with every title
    user_similarity = cosine_similarity(
        user_vector,
        tfidf_matrix
    ).flatten()

    # Rank titles
    ranked_indices = user_similarity.argsort()[::-1]

    recommendations = []

    for index in ranked_indices:

        # Don't recommend titles already liked
        if index in liked_indices:
            continue

        recommendations.append({
            "title": catalogue_df.iloc[index]["title"],
            "media_type": catalogue_df.iloc[index]["media_type"],
            "similarity_score": round(
                user_similarity[index] * 100,
                2
            )
        })

        if len(recommendations) == top_n:
            break

    return pd.DataFrame(recommendations)

In [44]:
import numpy as np 
recommend_for_user(
    [
        "Spider-Man: Brand New Day",
        "Spider-Man: No Way Home",
        "Spider-Man: Homecoming"
    ],
    top_n=10
)

                                         title media_type  similarity_score
0                    Spider-Man: Far From Home      movie             51.25
1          Spider-Man: Across the Spider-Verse      movie             35.04
2                     The Amazing Spider-Man 2      movie             31.54
3                                   Spider-Man      movie             29.34
4                       The Amazing Spider-Man      movie             28.94
5                                 Spider-Man 2      movie             26.04
6  Doctor Strange in the Multiverse of Madness      movie             21.92
7                                   Iron Man 2      movie             21.36
8                                   Iron Man 3      movie             21.25
9                       Avengers: Infinity War      movie             20.97

In [45]:
baseline_recommendations = recommend_for_user(
    [
        "Spider-Man: Brand New Day",
        "Spider-Man: No Way Home",
        "Spider-Man: Homecoming"
    ],
    top_n=20
)

baseline_recommendations

                                          title media_type  similarity_score
0                     Spider-Man: Far From Home      movie             51.25
1           Spider-Man: Across the Spider-Verse      movie             35.04
2                      The Amazing Spider-Man 2      movie             31.54
3                                    Spider-Man      movie             29.34
4                        The Amazing Spider-Man      movie             28.94
5                                  Spider-Man 2      movie             26.04
6   Doctor Strange in the Multiverse of Madness      movie             21.92
7                                    Iron Man 2      movie             21.36
8                                    Iron Man 3      movie             21.25
9                        Avengers: Infinity War      movie             20.97
10                                 The Avengers      movie             20.54
11                   Captain America: Civil War      movie             20.11
12                                     Iron Man      movie             19.72
13                      Avengers: Age of Ultron      movie             19.68
14                           Marvel's Daredevil         tv             19.04
15                                Thunderbolts*      movie             18.93
16                               Thor: Ragnarok      movie             18.80
17                                 Spider-Man 3      movie             18.74
18           Captain America: The First Avenger      movie             18.58
19                               Captain Marvel      movie             17.74

In [46]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

catalogue_df[
    ["rating_norm", "popularity_norm"]
] = scaler.fit_transform(
    catalogue_df[
        ["vote_average", "popularity"]
    ]
)

print(
    catalogue_df[
        ["title", "vote_average", "rating_norm", "popularity", "popularity_norm"]
    ].head()
)

             title  vote_average  rating_norm  popularity  popularity_norm
0  The Maze Runner         7.190     0.625042     30.7066         0.013568
1     Forrest Gump         8.500     0.845804     35.5787         0.018214
2      Ratatouille         7.846     0.735592     31.2608         0.014096
3  Graphic Desires         7.000     0.593023     38.3307         0.020839
4           Kraken         6.325     0.479272     94.4635         0.074374

In [47]:
def hybrid_recommend_for_user(liked_titles, top_n=10):

    liked_indices = []

    for title in liked_titles:

        matches = catalogue_df[
            catalogue_df["title"].str.lower() == title.lower()
        ]

        if matches.empty:
            print(f"⚠️ Title not found: {title}")
        else:
            liked_indices.append(matches.index[0])

    if not liked_indices:
        print("❌ No valid titles found.")
        return pd.DataFrame()

    # User taste vector
    liked_vectors = tfidf_matrix[liked_indices]

    user_vector = np.asarray(
        liked_vectors.mean(axis=0)
    )

    # Content similarity
    content_scores = cosine_similarity(
        user_vector,
        tfidf_matrix
    ).flatten()

    # Hybrid score
    final_scores = (
        0.70 * content_scores
        + 0.20 * catalogue_df["rating_norm"].values
        + 0.10 * catalogue_df["popularity_norm"].values
    )

    # Rank
    ranked_indices = final_scores.argsort()[::-1]

    recommendations = []

    for index in ranked_indices:

        # Don't recommend already liked titles
        if index in liked_indices:
            continue

        recommendations.append({
            "title": catalogue_df.iloc[index]["title"],
            "media_type": catalogue_df.iloc[index]["media_type"],
            "content_score": round(
                content_scores[index] * 100, 2
            ),
            "rating": catalogue_df.iloc[index]["vote_average"],
            "final_score": round(
                final_scores[index] * 100, 2
            )
        })

        if len(recommendations) == top_n:
            break

    return pd.DataFrame(recommendations)

In [48]:
hybrid_recommend_for_user(
    [
        "Spider-Man: Brand New Day",
        "Spider-Man: No Way Home",
        "Spider-Man: Homecoming"
    ],
    top_n=10
)

,title,media_type,content_score,rating,final_score
0,Spider-Man: Far From Home,movie,51.25,7.394,49.95
1,Spider-Man: Across the Spider-Verse,movie,35.04,8.341,41.41
2,Spider-Man,movie,29.34,7.342,34.93
3,The Amazing Spider-Man 2,movie,31.54,6.553,33.07
4,The Amazing Spider-Man,movie,28.94,6.749,32.06
5,Spider-Man 2,movie,26.04,7.324,31.37
6,Avengers: Infinity War,movie,20.97,8.200,31.31
7,The Avengers,movie,20.54,8.065,30.45
8,Marvel's Daredevil,tv,19.04,8.172,29.49
9,INVINCIBLE,tv,16.03,8.637,29.14

In [2]:
from sentence_transformers import SentenceTransformer

e:\ML\Movie\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [3]:
embedding_model = SentenceTransformer("all-MiniLM-L6-v2")

print("✅ Embedding model loaded")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
e:\ML\Movie\.venv\Lib\site-packages\huggingface_hub\file_download.py:141: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\anike\.cache\huggingface\hub\models--sentence-transformers--all-MiniLM-L6-v2. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 3573.07it/s]

✅ Embedding model loaded

In [10]:
import pandas as pd

catalogue_df = pd.read_csv(
    "../data/processed/movies_421_enriched.csv"
)

print("Dataset shape:", catalogue_df.shape)

Dataset shape: (421, 16)

In [12]:
import os

print(os.listdir("../data/processed"))

['movies_421_enriched.csv', 'movies_421_enriched.json', 'movies_enriched.csv', 'movies_enriched.json', 'movie_tv_catalogue.csv', 'movie_tv_catalogue.json']

In [14]:
catalogue_df = pd.read_csv(
    "../data/processed/movie_tv_catalogue.csv"
)

print("Dataset shape:", catalogue_df.shape)

Dataset shape: (860, 18)

In [15]:
print(catalogue_df.columns.tolist())

['id', 'title', 'overview', 'genres', 'keywords', 'cast', 'director', 'runtime', 'release_date', 'vote_average', 'vote_count', 'popularity', 'poster_path', 'backdrop_path', 'original_language', 'media_type', 'number_of_seasons', 'number_of_episodes']

In [16]:
catalogue_df["combined_text"] = (
    catalogue_df["overview"].fillna("") + " " +
    catalogue_df["genres"].fillna("") + " " +
    catalogue_df["keywords"].fillna("") + " " +
    catalogue_df["cast"].fillna("") + " " +
    catalogue_df["director"].fillna("")
)

print(
    catalogue_df[["title", "combined_text"]].iloc[0]
)

title                                              The Maze Runner
combined_text    A teenager with no memory of his past finds hi...
Name: 0, dtype: str

In [17]:
print("Missing combined_text:",
      catalogue_df["combined_text"].isna().sum())

print("Total records:",
      len(catalogue_df))

Missing combined_text: 0
Total records: 860

In [18]:
semantic_embeddings = embedding_model.encode(
    catalogue_df["combined_text"].tolist(),
    show_progress_bar=True
)

print("Embedding Shape:", semantic_embeddings.shape)

Batches: 100%|██████████| 27/27 [01:00<00:00,  2.24s/it]

Embedding Shape: (860, 384)

In [19]:
print("Vector length:", len(semantic_embeddings[0]))

Vector length: 384

In [20]:
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np
import pandas as pd

def semantic_recommend_for_user(liked_titles, top_n=10):

    liked_indices = []

    for title in liked_titles:
        matches = catalogue_df.index[
            catalogue_df["title"].str.lower() == title.lower()
        ].tolist()

        if matches:
            liked_indices.append(matches[0])
        else:
            print(f"Movie not found: {title}")

    if not liked_indices:
        print("No valid movies found.")
        return pd.DataFrame()

    # Get embeddings of liked movies
    liked_vectors = semantic_embeddings[liked_indices]

    # Create user preference vector
    user_vector = liked_vectors.mean(axis=0).reshape(1, -1)

    # Compare with every movie
    similarities = cosine_similarity(
        user_vector,
        semantic_embeddings
    ).flatten()

    # Don't recommend movies already liked
    similarities[liked_indices] = -1

    # Get top recommendations
    top_indices = np.argsort(similarities)[::-1][:top_n]

    recommendations = catalogue_df.iloc[top_indices][
        ["title", "media_type"]
    ].copy()

    recommendations["semantic_score"] = (
        similarities[top_indices] * 100
    ).round(2)

    recommendations.reset_index(drop=True, inplace=True)

    return recommendations

In [21]:
semantic_recommend_for_user(
    [
        "Spider-Man: Brand New Day",
        "Spider-Man: No Way Home",
        "Spider-Man: Homecoming"
    ],
    top_n=10
)

                            title media_type  semantic_score
0          The Amazing Spider-Man      movie       89.430000
1                    Spider-Man 2      movie       86.419998
2       Spider-Man: Far From Home      movie       86.260002
3                      Spider-Man      movie       85.440002
4        The Amazing Spider-Man 2      movie       85.279999
5                    Spider-Man 3      movie       83.839996
6            Ant-Man and the Wasp      movie       83.669998
7     The Punisher: One Last Kill      movie       81.260002
8  Guardians of the Galaxy Vol. 3      movie       80.820000
9                         Ant-Man      movie       80.760002

In [22]:
semantic_results = semantic_recommend_for_user(
    [
        "Spider-Man: Brand New Day",
        "Spider-Man: No Way Home",
        "Spider-Man: Homecoming"
    ],
    top_n=10
)

semantic_results

                            title media_type  semantic_score
0          The Amazing Spider-Man      movie       89.430000
1                    Spider-Man 2      movie       86.419998
2       Spider-Man: Far From Home      movie       86.260002
3                      Spider-Man      movie       85.440002
4        The Amazing Spider-Man 2      movie       85.279999
5                    Spider-Man 3      movie       83.839996
6            Ant-Man and the Wasp      movie       83.669998
7     The Punisher: One Last Kill      movie       81.260002
8  Guardians of the Galaxy Vol. 3      movie       80.820000
9                         Ant-Man      movie       80.760002

In [25]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(
    stop_words="english",
    max_features=10000
)

tfidf_matrix = tfidf.fit_transform(
    catalogue_df["combined_text"]
)

print("TF-IDF Matrix Shape:", tfidf_matrix.shape)

TF-IDF Matrix Shape: (860, 10000)

In [26]:
print("Catalogue:", catalogue_df.shape)
print("TF-IDF:", tfidf_matrix.shape)
print("Semantic:", semantic_embeddings.shape)

Catalogue: (860, 19)
TF-IDF: (860, 10000)
Semantic: (860, 384)

In [27]:
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np
import pandas as pd


def hybrid_recommend_for_user(liked_titles, top_n=10):

    liked_indices = []

    # Find liked titles
    for title in liked_titles:

        matches = catalogue_df.index[
            catalogue_df["title"].str.lower() == title.lower()
        ].tolist()

        if matches:
            liked_indices.append(matches[0])
        else:
            print(f"Movie not found: {title}")

    if not liked_indices:
        print("No valid titles found.")
        return pd.DataFrame()

    # ------------------------------------------------
    # 1. TF-IDF CONTENT SCORE
    # ------------------------------------------------

    liked_tfidf = tfidf_matrix[liked_indices]

    user_tfidf = np.asarray(
        liked_tfidf.mean(axis=0)
    )

    content_scores = cosine_similarity(
        user_tfidf,
        tfidf_matrix
    ).flatten()


    # ------------------------------------------------
    # 2. SEMANTIC SCORE
    # ------------------------------------------------

    liked_semantic = semantic_embeddings[liked_indices]

    user_semantic = (
        liked_semantic
        .mean(axis=0)
        .reshape(1, -1)
    )

    semantic_scores = cosine_similarity(
        user_semantic,
        semantic_embeddings
    ).flatten()


    # ------------------------------------------------
    # 3. NORMALIZE SCORES
    # ------------------------------------------------

    content_scores = (
        content_scores / content_scores.max()
    )

    semantic_scores = (
        semantic_scores / semantic_scores.max()
    )


    # ------------------------------------------------
    # 4. RATING SCORE
    # ------------------------------------------------

    rating_scores = (
        catalogue_df["vote_average"]
        .fillna(0)
        .values / 10
    )


    # ------------------------------------------------
    # 5. FINAL HYBRID SCORE
    # ------------------------------------------------

    final_scores = (
        0.35 * content_scores +
        0.50 * semantic_scores +
        0.15 * rating_scores
    )


    # ------------------------------------------------
    # 6. REMOVE ALREADY LIKED TITLES
    # ------------------------------------------------

    final_scores[liked_indices] = -1


    # ------------------------------------------------
    # 7. TOP RECOMMENDATIONS
    # ------------------------------------------------

    top_indices = np.argsort(
        final_scores
    )[::-1][:top_n]


    recommendations = catalogue_df.iloc[
        top_indices
    ][
        ["title", "media_type", "vote_average"]
    ].copy()


    recommendations["content_score"] = (
        content_scores[top_indices] * 100
    ).round(2)

    recommendations["semantic_score"] = (
        semantic_scores[top_indices] * 100
    ).round(2)

    recommendations["final_score"] = (
        final_scores[top_indices] * 100
    ).round(2)


    recommendations.reset_index(
        drop=True,
        inplace=True
    )

    return recommendations

In [28]:
hybrid_results = hybrid_recommend_for_user(
    [
        "Spider-Man: Brand New Day",
        "Spider-Man: No Way Home",
        "Spider-Man: Homecoming"
    ],
    top_n=10
)

hybrid_results

,title,media_type,vote_average,content_score,semantic_score,final_score
0,Spider-Man: Far From Home,movie,7.394,60.00,90.230003,77.20
1,The Amazing Spider-Man,movie,6.749,40.75,93.550003,71.16
2,Spider-Man: Across the Spider-Verse,movie,8.341,47.46,83.339996,70.79
3,Spider-Man,movie,7.342,37.26,89.370003,68.74
4,The Amazing Spider-Man 2,movie,6.553,39.92,89.199997,68.40
5,Spider-Man 2,movie,7.324,34.11,90.389999,68.12
6,The Avengers,movie,8.065,27.55,82.199997,62.84
7,Spider-Man 3,movie,6.472,26.11,87.699997,62.69
8,The Punisher: One Last Kill,movie,8.297,21.87,84.989998,62.60
9,Iron Man,movie,7.663,26.71,83.010002,62.34

In [29]:
import pickle

with open("../data/processed/tfidf_vectorizer.pkl", "wb") as f:
    pickle.dump(tfidf, f)

with open("../data/processed/tfidf_matrix.pkl", "wb") as f:
    pickle.dump(tfidf_matrix, f)

with open("../data/processed/semantic_embeddings.pkl", "wb") as f:
    pickle.dump(semantic_embeddings, f)

catalogue_df.to_pickle(
    "../data/processed/catalogue_df.pkl"
)

print("✅ ML components saved")

✅ ML components saved